import MainLayout from "@/layouts/MainLayout";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Martech FE Quiz Test",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased "w-screen relative overflow-x-hidden min-h-screen bg-gray-100 scrollbar-hide analytics-dashboard-1-page dark:bg-[#000]"`}
      >
        <MainLayout>{children}</MainLayout>
      </body>
    </html>
  );
}
